// <auto-generated />
namespace Pratice.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805040116028_addedtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
